### ISSUE TITLE
Support imports for classes from .jar files

### ISSUE THREAD

**Issue by widgetii** [prominic/groovy-language-server#2]
Hi Josh!

Great work, I've found it on GitHub and it conquered my heart) Is it possible to include DSL specific class imports into LSP configs to seamlessly work with, for example, Jenkins groovy scripts?

Now it give me warnings "unable to resolve class xxx" for different imports like:
import jenkins.model.Jenkins
import net.sf.json.JSONObject

and so on

**Comment by joshtynjala** [comment]
@widgetii I assume that these classes that you want to use are defined in a *.jar* file? The default [`CompilationUnitFactory`](https://github.com/prominic/groovy-language-server/blob/master/src/main/java/net/prominic/groovyls/config/CompilationUnitFactory.java) only supports *.groovy* files with no support for *.jar* libraries. However, it's possible to create a custom `ICompilationUnitFactory` that is more powerful.

The default `CompilationUnitFactory` is basically meant to be an example only, and then people who want to add Groovy support to a new IDE can provide a custom `ICompilationUnitFactory` that loads the appropriate classpaths and other configuration options from their own project files.

You could probably copy/paste the default `CompilationUnitFactory` into a new class and add support for *.jar* files pretty easily. In `create()`, where the `CompilerConfiguration` object is created, you can pass a list of classpaths to the `setClasspathList()` method:

``` java
ArrayList<String> libraries = new ArrayList<>();
libraries.add("path/to/somefile.jar");
libraries.add("path/to/somefolder/*");
config.setClasspathList(libraries);
```

It's up to you where you get the list of classpaths, but that's basically how it works.

**Comment by widgetii** [comment]
@joshtynjala Great suggestions!
I was able to unpack jenkins.war, extract all jars from WEB-INF/lib and include them into language server using your method. Errors about class resolving are gone, but unfortunately autocompletion still doesn't work properly: I get only basic suggestions on object methods (wait, notify and so on)

<img width="778" alt="Screenshot 2019-07-02 at 20 21 24" src="https://user-images.githubusercontent.com/6576495/60533423-41c15800-9d08-11e9-93c8-2d43ef2a852a.png">

I believe in case of value returned by System.getenv() it need to be detected as map but not as java.lang.Object. This is same for jenkins object 

<img width="351" alt="Screenshot 2019-07-02 at 20 29 30" src="https://user-images.githubusercontent.com/6576495/60533504-73d2ba00-9d08-11e9-9dcf-8e792bd80f8f.png">

Do I need to add something also?

**Comment by joshtynjala** [comment]
Currently, variables that use `def` are always be typed as `Object`. That's what the Groovy compiler returns from the AST for the variable's type. Maybe I can try to resolve the type of the value that is assigned when using `def`, or maybe there's another way to ask for the type. I'll need to look into it.

For now, the only workaround that I can think of is to use the real type instead of `def`.

**Comment by joshtynjala** [comment]
@widgetii I think my most recent commits will get types properly resolving with `def` variables. Give it a try and let me know how it works for you!

**Comment by widgetii** [comment]
@joshtynjala Now it's better but:

1) It seems that env variable detected as String but in our case this is a [map](https://www.logicbig.com/how-to/code-snippets/jcode-java-system-getenv.html)
<img width="341" alt="Screenshot 2019-07-03 at 10 20 04" src="https://user-images.githubusercontent.com/6576495/60571513-6f47e900-9d7c-11e9-8d66-eeb937d21b47.png">

2) Jenkins object still has no autocompletion due to unable to detect type of value returned by [Jenkins.getInstance()](https://javadoc.jenkins.io/jenkins/model/Jenkins.html#getInstance--) method
<img width="336" alt="Screenshot 2019-07-03 at 10 24 34" src="https://user-images.githubusercontent.com/6576495/60571977-3d835200-9d7d-11e9-88c2-9c55108ed53b.png">

**Comment by joshtynjala** [comment]
Hmmm... looks like it's using the return value from the wrong overload. I'll take a look at both of those soon.

**Comment by joshtynjala** [comment]
@widgetii Give my latest commit a try! It should fix your issue.

**Comment by widgetii** [comment]
@joshtynjala Great work!
Both problem are gone. 

Could we also do something with original problem about including custom jars with classes to language server. Due to embedding nature of Groovy I feel it would be first question in future FAQ. Modifying sources and add necessary libraries is good option but It would be more convenient to pass them in command line.

**Comment by joshtynjala** [comment]
Yeah, I understand.

In Moonshine IDE, we're using a custom `ICompilationUnitFactory` that parses *.classpath* files from Eclipse to figure out which *.jar* files to add. We run the `gradle eclipse` command to create the Eclipse project before we launch the language server. I'm considering moving some of that code upstream, directly into groovy-language-server. Maybe not enabled by default, but available if desired.

Like you said, a command line option could be good. The language server protocol also supports configuration settings, so that might be an option too.

I still need to think about it some more.

**Comment by paoloantinori** [comment]
Hi, 
to begin with, thanks for your work!

I'm testing it in vscode and I'm fighting with the same this same use case.

In my case something even stranger happened:

this basic example stopped working:
```def env = System.getEnv();
env.
```

showing now only the methods coming from `Object`

I'm pretty sure this worked, since I have a local screenshot I took that proves it but it suddenly stopped.
I have no explanation for this if not something related to non determinism in a possible non sorted collection? (I'm just guessing here)

Can I ask you to confirm that this use case works for you or guide me to how I could help with debugging the problem?

thank you

**Comment by paoloantinori** [comment]
To be more precise, and hopefully more helpful, this tests fails on my system when added to https://github.com/prominic/groovy-language-server/blob/master/src/test/java/net/prominic/groovyls/GroovyServicesCompletionTests.java:

```java

@Test
void testDynamicTyping() throws Exception {
    Path filePath = srcRoot.resolve("Completion.groovy");
    String uri = filePath.toUri().toString();
    StringBuilder contents = new StringBuilder();
    contents.append("def env = System.getEnv();\n");
    contents.append("env.");
    TextDocumentItem textDocumentItem = new TextDocumentItem(uri, LANGUAGE_GROOVY, 1, contents.toString());
    services.didOpen(new DidOpenTextDocumentParams(textDocumentItem));
    TextDocumentIdentifier textDocument = new TextDocumentIdentifier(uri);
    Position position = new Position(1, 4);
    Either<List<CompletionItem>, CompletionList> result = services
            .completion(new CompletionParams(textDocument, position)).get();
    Assertions.assertTrue(result.isLeft());
    List<CompletionItem> items = result.getLeft();
    Assertions.assertTrue(items.size() > 0);
    List<CompletionItem> filteredItems = items.stream().filter(item -> {
        return item.getLabel().equals("containsKey") && item.getKind().equals(CompletionItemKind.Method);
    }).collect(Collectors.toList());
    Assertions.assertEquals(1, filteredItems.size());
}
```

**Comment by joshtynjala** [comment]
The new `groovy.classpath` setting now allows custom .jar files to be added. Closing.
