### ISSUE TITLE
What is the minimum requirements to build this?

### ISSUE THREAD

**Issue by thepenguinthatwants** [prominic/groovy-language-server#20]
Hi!

I have two computers and one could build this fine but another doesnt react.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/daemon/Downloads/groovy-language-server/build.gradle'

* What went wrong:
Could not compile build file '/home/groover/Downloads/groovy-language-server/build.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 57

**Comment by thepenguinthatwants** [comment]
Oh so it seems to be java 11 version that supported java 13 fails.
Yet I dont seem to get vim or from terminal to show any bracket errors from jenkinsfile or *.groovyfiles..

**Comment by joshtynjala** [comment]
This project currently targets Java 1.8.

A quick web search seems to indicate that you may need to upgrade Gradle after you upgrade to Java 13. Which version of Gradle do you have installed? I saw one person mention that Gradle did not support Java 13 until 6.0 RC1.

**Comment by thepenguinthatwants** [comment]
Earlier I used jdk11-openjdk and jdk13-openjdk. I think they differ from the java 1.8?

I am using gradle 6.1.1-1

**Comment by joshtynjala** [comment]
I just updated the Gradle wrapper to 6.0. I think that may fix your issue with Java 13. Let me know!

**Comment by thepenguinthatwants** [comment]
Hi!

Yeh it seems to build! Tho not sure if it works correctly. 

Any way to easy test if it works on a groovyfile?

**Comment by joshtynjala** [comment]
If you hover the mouse over a symbol, like a variable or a type, you should see a tool-tip with some information about the symbol.

**Comment by thepenguinthatwants** [comment]
I was wondering if this has linting ability?

I am using this with vim and coc.vim plugin. But it doesnt seem to do anything. Is it possible to invoke by terminal and see some responses?

**Comment by joshtynjala** [comment]
This language server integrates with the Groovy compiler, but not any linters.


In the [instructions that I wrote for Sublime Text](https://github.com/prominic/groovy-language-server/tree/master/sublime-text), you can see how the language server is launched:

```sh
java -jar groovy-language-server-all.jar
```

You should be able to launch it similarly in other editors, I guess. However, they probably all have their own unique ways of setting up a new language server, so that's basically all of the advice I can give.

It may be possible to interact with the language server from a terminal, but you'd need to manually send it appropriately-formed LSP messages in the right order. Even as someone who knows the LSP pretty well, I wouldn't bother trying that.

**Comment by thepenguinthatwants** [comment]
With nvim I get 

`failed to start: Internal error`

So I was wondering if there is a way to open it as verbose mode to check whats wrong.
