### ISSUE TITLE
publish VsCode extension

### ISSUE THREAD

**Issue by luk355** [prominic/groovy-language-server#4]
Thanks for your effort, Josh, to put this together.

I was hoping to use the VsCode extension, however, I am unable to find it on [VsCode marketplace](https://marketplace.visualstudio.com/search?term=groovy&target=VSCode&category=All%20categories&sortBy=Relevance). Has the extension been published there and if not, do you have any plans getting it published soon?

**Comment by joshtynjala** [comment]
The VSCode extension is not published on the Marketplace, and I don't have plans to publish it.

This language server was originally developed for a different editor, Moonshine IDE. The example VSCode extension included in the repository is mainly meant to allow me to test that the language server correctly follows the language server protocol by testing in another editors besides Moonshine.

It can also serve as an example of how someone might get started on creating a proper VSCode extension. It's really the bare minimum required to get something running VSCode, and I won't be adding any configuration options or any tighter VSCode integration. Unfortunately, I don't have the bandwidth to maintain and support a full extension for VSCode.

That being said, I'll try to find some time to update the build script so that it creates a *.vsix* file that people can manually install in VSCode.

**Comment by luk355** [comment]
Thanks for the update Josh. I would really appreciate if you can find time to update the build scripts so that the *.vsix* file is produced. I will then take it see if I can produce something publishable to VSCode marketplace.

Cheers!
